Update InstallAppRequest type to new format
holochain/holochain-client-js pull request #298
Opened 2024-11-25 12:37 UTC by matthme

This PR contains the type changes required in order to adhere to https://github.com/holochain/holochain/pull/4416 and its follow-up PR https://github.com/holochain/holochain/pull/4488

2024-11-25 15:46 UTC, jost-s requested changes
Please add a test or modify an existing one that uses roles_settings.

2024-11-25 22:05 UTC, matthme commented
I'm confused - why do the tests even pass? Are the tests not actually ran in CI?

2024-11-25 22:10 UTC, jost-s commented
The tests pass because `memproofs` is just ignored and `roles_settings` is optional.

2024-11-26 15:14 UTC, matthme commented
Test added.

2024-11-26 15:31 UTC, matthme commented
Hmm...actually the problem that `Uint8Array`s don't deserialize to `YamlProperties` is a problem. This means that you can't even pass in agent public keys there unless you base64 encode them or conver them to an `Array<number>`.

2024-11-26 18:07 UTC, matthme commented on test/e2e/index.ts
> +            properties: yaml.dump({ progenitor: progenitorKey }),
Changed the test now to use a yaml string.
cc @ThetaSinner

2024-11-26 18:09 UTC, matthme commented
Okay never mind. I think this is totally appropriate and the app developer can be expected to take care of any required conversion for example using `js-yaml` (we just need to make sure that the js-client actually returns a useful error which is not currently the case https://github.com/holochain/holochain-client-js/issues/299).

2024-11-26 22:08 UTC, jost-s requested changes
LGTM
a suggestion for the yaml properties type and some cleanup

2024-11-26 22:08 UTC, jost-s commented on package.json
> +    "js-yaml": "4.1.0",
This can be a dev dependency too.

2024-11-26 22:08 UTC, jost-s commented on src/api/admin/types.ts
> +// eslint-disable-next-line @typescript-eslint/no-explicit-any
Is this needed here? It should only produce a warning.
Actually `unknown` would be the idiomatic type.

2024-11-26 22:08 UTC, jost-s commented on test/e2e/common.ts
> +    roles_settings: {},
`roles_settings` is optional
```suggestion
    roles_settings: {},
```

2024-11-26 22:08 UTC, jost-s commented on test/e2e/common.ts
> +    roles_settings: {},
```suggestion
```

2024-11-26 22:08 UTC, jost-s commented on test/e2e/index.ts
> +      roles_settings: {},
and so on further down
```suggestion
```

2024-11-26 22:08 UTC, jost-s commented on test/e2e/index.ts
> +      cap_secret: undefined,
```suggestion
```

2024-11-26 22:27 UTC, matthme commented
Thank you! Addressed all of these now.

2024-11-26 23:10 UTC, jost-s requested changes
Just a few more bits

2024-11-26 23:10 UTC, jost-s commented on Cargo.toml
> +hdk = "0.5.0-dev.6"
This is intentionally kept at `.0` as long as there are no breaking changes in the HDK.

2024-11-26 23:10 UTC, jost-s commented on test/e2e/common.ts
> +    roles_settings: {},
I'm still here =)

2024-11-28 17:05 UTC, matthme commented on Cargo.toml
> +hdk = "0.5.0-dev.6"
Alright!

2024-11-28 17:06 UTC, matthme commented
search and replace for the win.

2024-11-28 18:10 UTC, jost-s requested changes

2024-11-28 18:10 UTC, jost-s commented on test/e2e/common.ts
> +    roles_settings: {},
And still here

2024-11-28 18:10 UTC, jost-s commented on test/e2e/common.ts
> +    roles_settings: {},
Delete me

2024-11-28 18:12 UTC, matthme commented on test/e2e/common.ts
> +    roles_settings: {},
done.

2024-11-28 18:45 UTC, jost-s approved these changes

2024-11-28 19:48 UTC, merged