Backport: New install app payload
holochain/holochain-client-js pull request #300
Opened 2024-11-28 19:57 UTC by matthme

2024-11-28 20:10 UTC, matthme commented on test/e2e/index.ts
> +test(
I'm assuming that this was accidental...

2024-11-28 21:35 UTC, jost-s commented
I've fixed the tests now that DPKI is no longer present.

2024-11-28 23:09 UTC, matthme commented
Looks like tests passed - is it approvable now? =D

2024-11-28 23:11 UTC, jost-s requested changes
One change please

2024-11-28 23:11 UTC, jost-s commented on Cargo.toml
> +hdk = "0.4.0-rc.1"
please revert this

2024-11-28 23:12 UTC, matthme commented on Cargo.toml
> +hdk = "0.4.0-rc.1"
It was actually necessary due to the __hc_preflight_request function I think.

2024-11-28 23:12 UTC, matthme commented on Cargo.toml
> +hdk = "0.4.0-rc.1"
Tests would fail otherwise

2024-11-28 23:16 UTC, matthme commented on Cargo.toml
> +hdk = "0.4.0-rc.1"
Hmm...I cannot reproduce it anymore. I reverted it. But I did get that error at some point and thought I had to bump the hdk for it to work...

2024-11-29 00:58 UTC, jost-s approved these changes

2024-11-29 10:11 UTC, merged