update holochain script
holochain/holochain-client-js pull request #67
Opened 2021-04-26 12:14 UTC by zo-el

2021-04-26 15:59 UTC, Connoropolous commented on Makefile
> +		echo "✔  Updating holo-nixpkgs rev in nixpkgs.nix...";\
these seem out of place

2021-04-26 16:00 UTC, Connoropolous commented on Makefile
> +		echo "No holo-nixpkgs rev provided"; \
This also seems like a misleading comment

2021-05-04 18:01 UTC, zippy approved these changes

2021-05-04 18:01 UTC, zippy commented on Makefile
> +		echo "No holo-nixpkgs rev provided"; \
```suggestion
		echo "No holochain rev provided"; \
```

2021-05-04 18:06 UTC, zippy requested changes
the script also needs to update the holochain rev values in the README in default.nix, and in test/e2e/fixutres/zomes/foo/Cargo.toml

2021-05-05 17:36 UTC, zippy approved these changes

2021-05-06 04:56 UTC, merged