Add eslint as code formatter
holochain/holochain-client-js pull request #79
Opened 2021-08-04 04:40 UTC by jost-s

Regarding #21 

I've added eslint and linted the code based on predominant style (single and double quotes as well as semi-colons and no semi-colons were mixed). We can swap that around depending on your preference =)

We can add prettier as well if you want.

I replaced a few unspecific types.

2021-09-15 20:23 UTC, zippy requested changes
This is great, thank you.  Just one request, that we don't force a quote style.   I'm fine with having them cleaned up in this one PR but in general I like the flexibility so that I can do both strings like this:
```
x = "test = 'fish'"
y = '<tag attr="dog">'
```
depending on what I don't want to have to quote.

2021-09-15 20:23 UTC, zippy commented on .eslintrc.js
> +    'quotes': ['error', 'single'],
I would rather not enforce one quote style.  There are often reasons to use one vs the other, i.e. depending on if you want to quote or not quote the singe or double quotes in a particular string.

2021-09-16 04:52 UTC, jost-s commented
Hi @zippy, in those cases where different quotes are needed, the back tick can be used
```javascript
x = `test = 'fish'`
y = `<tag attr="dog">`
```
Nevertheless I've removed the quote rule and reverted the affected lines.

Ready for review again.

2021-09-21 19:48 UTC, zippy approved these changes
Looks great, just the packge.lock merge conflicts and ready to go.

2021-09-22 19:38 UTC, jost-s commented
@zippy Super, resolved. A few more files were linted after the most recent commit.

2021-10-27 20:21 UTC, merged